on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-18.04
        strategy:
            matrix:
                python-version: [3.5, 3.6]

        steps:
            - name: Git Checkout
              uses: actions/checkout@v2
              with:
                  submodules: recursive

            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Build PICT
              run: |
                  pushd pict
                  make libpict.so
                  make pict
                  popd
                  echo "${PWD}" >> $GITHUB_PATH
                  echo "LD_LIBRARY_PATH=${PWD}" >> $GITHUB_ENV

            - name: Install Python libraries
              run: |
                  pip install Cython coveralls

            - name: Install PyPICT
              run: |
                  pip install -vvv .

            - name: Run tests
              run: |
                  coverage run -p setup.py test

            - name: Submit coverage report
              run: |
                  coverage combine
                  coveralls
